name: MorHam Technologies
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61195
title: MorHam Technologies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1bece'
    - '#dad9d7'
    - '#676d7b'
    - '#3a3937'
    - '#1c1c1c'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
